=== ykarim/WeatherWatch/WeatherWatch/src/main/resources/imageLocations.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT imageLocations (thunderstorm, drizzle, rain, snow, atmosphere, clear, extreme)>
        <!ELEMENT thunderstorm (#PCDATA)>
        <!ELEMENT drizzle (#PCDATA)>
        <!ELEMENT rain (#PCDATA)>
        <!ELEMENT snow (#PCDATA)>
        <!ELEMENT atmosphere (#PCDATA)>
        <!ELEMENT clear (#PCDATA)>
        <!ELEMENT extreme (#PCDATA)>

=== ykarim/WeatherWatch/WeatherWatch/src/main/resources/imageLocations.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE imageLocations SYSTEM "imageLocations.dtd">
<imageLocations>
    <thunderstorm>weatherBackgrounds/lightning.jpeg</thunderstorm>
    <drizzle>weatherBackgrounds/drizzle.jpg</drizzle>
    <rain>weatherBackgrounds/rain.jpeg</rain>
    <snow>weatherBackgrounds/snow.jpeg</snow>
    <atmosphere>weatherBackgrounds/fog.jpg</atmosphere>
    <clear>weatherBackgrounds/clear.jpeg</clear>
    <extreme>weatherBackgrounds/extreme.jpeg</extreme>
</imageLocations>
